import Head from 'next/head';
import { Footer } from '../components/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blogroll.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Blogroll.js</span>
        </h1>

        <p className={styles.description}>
          A curated list of blog articles about the JS ecosystem and modern Web
          Dev.
        </p>

        <div className={styles.grid}>
          <a
            className={styles.card}
            href="https://nextjs.org/docs"
            target="_blank"
            rel="noreferrer"
          >
            <p>How to Manage JavaScript Fatigue</p>
          </a>

          <a
            className={styles.card}
            href="https://nextjs.org/learn"
            target="_blank"
            rel="noreferrer"
          >
            <p>
              React Architecture: How to Structure and Organize a React
              Application
            </p>
          </a>

          <a
            className={styles.card}
            href="https://nextjs.org/learn"
            target="_blank"
            rel="noreferrer"
          >
            <p>The Comprehensive Guide to JavaScript Design Patterns</p>
          </a>
        </div>
      </main>
      <Footer />
    </div>
  );
}
